services:
  static-images:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file: .env
    environment:
      NODE_ENV: "production"
    volumes:
      - "fileUpload:/home/image-service/upload/${IMAGE_DIR}"
    command: [ "node", "dist/src/app.js" ]
volumes:
  fileUpload: